name: temp
description: A note-taking application with social features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.3.3
  crypto: ^3.0.3
  intl: ^0.20.2
  mime: ^1.0.2
  open_file: ^3.2.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  file_picker: 10.1.5
  flutter_plugin_android_lifecycle: ^2.0.17
  flutter_image_compress: ^2.4.0
  win32: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
