services:
  api:
    build: .
    container_name: backend_notenest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=notenest
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=notenest_mongo
    depends_on:
      - mysql
      - mongodb
    networks:
      - notenest_network

  mysql:
    image: mysql:8.0
    container_name: mysql_container_notenest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notenest
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notenest_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb_notenest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=notenest_mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - notenest_network

networks:
  notenest_network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
